### ISSUE TITLE
Trouble building

### ISSUE THREAD

**Issue by bapti** [bphudson1984/FMPTechTest#1]
Hi Ben, @bphudson1984 

Software architect at FindMyPast here, I pulled down your solution to build it but it's missing a couple of files so it won't build.  Could you add them in?  

![image](https://cloud.githubusercontent.com/assets/1849893/9997199/c987d2d0-6082-11e5-9c18-f78ad8150ec9.png)

Cheers
Neil

**Comment by bphudson1984** [comment]
Hey,

Thanks for taking the time to look through my submission.

It's a bit odd that both of these files are missing, i.e the BoardRenderer and the corresponding unit test class.

Unfortunately, I am at work now and will probably be for at least another couple of hours.  The moment I get home I will ensure these are checked in.  These two files were part of my intial check-in, so perhaps something has gone amiss?  Either way, a little odd.

Apologies,

Ben Hudson

**Comment by bapti** [comment]
@bphudson1984 No worries, it happens to the best of us.  I'll have a look tomorrow morning, have a nice night.

Cheers
Neil

**Comment by bphudson1984** [comment]
Not the best start to a tech test though!  

If I had of set up a one click build system based off the github repository that compiled the code and ran all of the tests this would never have happened :P

Anyway, thanks for bearing with me.

Cheers

Ben

**Comment by bphudson1984** [comment]
Resolved.  Two files were untracked within VS.  Checked in now, hopefully you have no additional problems.
